# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\painelOpcao.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(396, 184)
        self.lbl_desc = QtWidgets.QLabel(Dialog)
        self.lbl_desc.setGeometry(QtCore.QRect(20, 60, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_desc.setFont(font)
        self.lbl_desc.setObjectName("lbl_desc")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(-3, 40, 401, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lbl_titulo = QtWidgets.QLabel(Dialog)
        self.lbl_titulo.setGeometry(QtCore.QRect(160, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lbl_icon = QtWidgets.QLabel(Dialog)
        self.lbl_icon.setGeometry(QtCore.QRect(100, 10, 51, 31))
        self.lbl_icon.setText("")
        self.lbl_icon.setObjectName("lbl_icon")
        self.btn_ok = QtWidgets.QPushButton(Dialog)
        self.btn_ok.setGeometry(QtCore.QRect(150, 150, 81, 23))
        self.btn_ok.setStyleSheet("border: 1px solid #333;\n"
"background-color: #8cb3d9;\n"
"color: #000;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.btn_ok.setObjectName("btn_ok")
        self.btn_report = QtWidgets.QPushButton(Dialog)
        self.btn_report.setGeometry(QtCore.QRect(270, 150, 121, 23))
        self.btn_report.setStyleSheet("background-color: #ffeb99;\n"
"border: 1px solid #adad85;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.btn_report.setObjectName("btn_report")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_desc.setText(_translate("Dialog", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia hendrerit turpis. Donec nec fringilla tortor, in dapibus dolor. Aenean vitae purus metus. Pellentesque et scelerisque ipsum. Ut ornare nisi velit, vitae venenatis felis condimentum sed. Cras bibendum nulla ut tempus sagittis. Praesent vel malesuada metus, in malesuada purus. Ut condimentum mi ac congue congue. Integer lacus magna, pulvinar laoreet condimentum id, finibus ut felis. Maecenas vel eros sed ante egestas iaculis. Curabitur vitae nulla sapien. Vestibulum felis felis, convallis id tincidunt nec,\n"
" lobortis ornare diam. \n"
"Praesent a dui quis dui maximus dapibus."))
        self.lbl_titulo.setText(_translate("Dialog", "Titulo"))
        self.btn_ok.setText(_translate("Dialog", "Ok"))
        self.btn_report.setText(_translate("Dialog", "Reportar"))
